<?php

namespace ermakk\likes\widgets\LikeButton;

use ermakk\likes\models\Likes;
use phpDocumentor\Reflection\Types\This;
use Yii;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class LikeButton extends Widget
{
    public $record = null;
    public $options = [];
    private $refOptions = [
        'moduleId' => 'votes'
    ];
    public $pluginOptions = [];
    private $refPluginOptions = [
        'actionClass' => 'like-button',
        'buttonClass' => 'like-true btn',
        'buttonClassTrueState' => 'btn-outline-secondary',
        'buttonClassFalseState' => 'btn-outline-primary',
        'icoTrueState' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                            </svg>',
        'icoFalseState' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                              <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                            </svg>',
        'counterClass' => 'count-likes',
    ];

    public $behaviors = [
        'beforeLike' => '',
        'afterLike' => '',
    ];

    public function init()
    {
        $this->options = array_merge($this->refOptions, $this->options);
        $this->pluginOptions = array_merge($this->refPluginOptions, $this->pluginOptions);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $likes = new Likes();
        $likes = $likes::find()->where(['user_id' => \Yii::$app->user->getId(), 'row_id' => $this->record->id, 'model' => get_class($this->record)])->one();
        $url = Url::toRoute([
            '/'.$this->options['moduleId'].'/like/toggle',
            'id' => $this->record->id,
            'class' => Yii::$app->getSecurity()->encryptByPassword(get_class($this->record), Yii::$app->getModule('votes')->token),
        ]);
        $count = (new Likes())::find()->where(['row_id' => $this->record->id, 'model' => get_class($this->record)])->count();

        return $this->render('index', [
            'likes' => $likes,
            'url' => $url,
            'count' => $count,
            'pluginOptions' => $this->pluginOptions,
            'behaviors' => $this->behaviors,
        ]);

    }
}